services:
  bitly_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - bitly_db_data:/var/lib/postgresql/data
    restart: always
  bitly:
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@bitly_db:5432/${DB_NAME}
    depends_on:
      - bitly_db
    restart: always

volumes:
  bitly_db_data: